
django.utils.autoreload INFO 2025-03-22 18:21:49,175 autoreload 95573 139836997738624 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-22 18:26:51,575 autoreload 97443 140639524647040 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-22 18:38:40,980 autoreload 101030 140322500759680 Watching for file changes with StatReloader
django.security.DisallowedHost ERROR 2025-03-22 18:38:44,291 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:44,307 log 101030 140322450437824 Bad Request: /home/accounts/login/
django.server WARNING 2025-03-22 18:38:44,307 basehttp 101030 140322450437824 "GET /home/accounts/login/ HTTP/1.1" 400 75229
django.security.DisallowedHost ERROR 2025-03-22 18:38:44,390 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:44,399 log 101030 140322450437824 Bad Request: /favicon.ico
django.server WARNING 2025-03-22 18:38:44,399 basehttp 101030 140322450437824 "GET /favicon.ico HTTP/1.1" 400 74760
django.security.DisallowedHost ERROR 2025-03-22 18:38:45,315 exception 101030 140322450437824 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
django.request WARNING 2025-03-22 18:38:45,323 log 101030 140322450437824 Bad Request: /home/accounts/login/
django.server WARNING 2025-03-22 18:38:45,324 basehttp 101030 140322450437824 "GET /home/accounts/login/ HTTP/1.1" 400 75229
django.utils.autoreload INFO 2025-03-22 18:39:03,940 autoreload 101030 140322500759680 /home/finn/Group-Engineering-Project/SustainableApplication/SustainableApplication/settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-22 18:39:04,116 autoreload 101211 140545121677440 Watching for file changes with StatReloader
django.server INFO 2025-03-22 18:39:05,765 basehttp 101211 140545071511232 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:39:05,820 basehttp 101211 140545071511232 "GET /static/auth.css HTTP/1.1" 200 1844
django.server INFO 2025-03-22 18:41:42,934 basehttp 101211 140545071511232 "GET /leaderboard/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 18:41:42,944 basehttp 101211 140545071511232 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:43,035 basehttp 101211 140545062069952 "GET /static/auth.css HTTP/1.1" 200 1844
django.server INFO 2025-03-22 18:41:43,045 basehttp 101211 140545071511232 "GET /static/images/signin.jpg HTTP/1.1" 200 482362
django.request WARNING 2025-03-22 18:41:43,295 log 101211 140545071511232 Not Found: /favicon.ico
django INFO 2025-03-22 18:41:43,969 views 101211 140545062069952 User asked for personal data stored: 
django.request ERROR 2025-03-22 18:41:43,981 log 101211 140545062069952 Internal Server Error: /home/accounts/view_data/
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/SustainableApplication/home/views.py", line 279, in view_user_data
    "hashed_password": user.password  # Django stores hashed passwords
                       ^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'password'
django.server ERROR 2025-03-22 18:41:43,982 basehttp 101211 140545062069952 "GET /home/accounts/view_data/ HTTP/1.1" 500 80788
django.request WARNING 2025-03-22 18:41:44,101 log 101211 140545062069952 Not Found: /favicon.ico
django.server INFO 2025-03-22 18:41:44,872 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:45,338 basehttp 101211 140545062069952 "GET /home/accounts/change_password/ HTTP/1.1" 200 6923
django.server INFO 2025-03-22 18:41:45,920 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:46,640 basehttp 101211 140545062069952 "GET /collectables/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 18:41:46,648 basehttp 101211 140545062069952 "GET /accounts/login/?next=/collectables/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:47,550 basehttp 101211 140545062069952 "GET /leaderboard/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 18:41:47,557 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django INFO 2025-03-22 18:41:48,135 views 101211 140545062069952 User asked for personal data stored: 
django.request ERROR 2025-03-22 18:41:48,143 log 101211 140545062069952 Internal Server Error: /home/accounts/view_data/
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/SustainableApplication/home/views.py", line 279, in view_user_data
    "hashed_password": user.password  # Django stores hashed passwords
                       ^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'password'
django.server ERROR 2025-03-22 18:41:48,144 basehttp 101211 140545062069952 "GET /home/accounts/view_data/ HTTP/1.1" 500 80788
django.server INFO 2025-03-22 18:41:48,923 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:49,375 basehttp 101211 140545062069952 "GET /home/accounts/change_password/ HTTP/1.1" 200 6923
django.server INFO 2025-03-22 18:41:49,943 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.request ERROR 2025-03-22 18:41:50,479 log 101211 140545062069952 Internal Server Error: /home/accounts/update_profile/
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/SustainableApplication/home/views.py", line 190, in update_profile
    form = CustomUserUpdateForm(instance=request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/forms/models.py", line 369, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/forms/models.py", line 110, in model_to_dict
    opts = instance._meta
           ^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute '_meta'
django.server ERROR 2025-03-22 18:41:50,480 basehttp 101211 140545062069952 "GET /home/accounts/update_profile/ HTTP/1.1" 500 85816
django.server INFO 2025-03-22 18:41:51,226 basehttp 101211 140545062069952 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:41:51,743 basehttp 101211 140545062069952 "GET /home/accounts/logout/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 18:41:51,751 basehttp 101211 140545062069952 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django.utils.autoreload INFO 2025-03-22 18:44:36,389 autoreload 101211 140545121677440 /home/finn/Group-Engineering-Project/SustainableApplication/SustainableApplication/settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-22 18:44:36,626 autoreload 102535 140700128727168 Watching for file changes with StatReloader
django.request ERROR 2025-03-22 18:58:11,500 log 102535 140700078307008 Internal Server Error: /home/accounts/update_profile/
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/SustainableApplication/home/views.py", line 190, in update_profile
    form = CustomUserUpdateForm(instance=request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/forms/models.py", line 369, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/forms/models.py", line 110, in model_to_dict
    opts = instance._meta
           ^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute '_meta'
django.server ERROR 2025-03-22 18:58:11,502 basehttp 102535 140700078307008 "GET /home/accounts/update_profile/ HTTP/1.1" 500 85802
django.request WARNING 2025-03-22 18:58:11,630 log 102535 140700078307008 Not Found: /favicon.ico
django.server INFO 2025-03-22 18:58:12,145 basehttp 102535 140700078307008 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django.server INFO 2025-03-22 18:58:12,751 basehttp 102535 140700078307008 "GET /home/accounts/change_password/ HTTP/1.1" 200 6923
django.server INFO 2025-03-22 18:58:13,387 basehttp 102535 140700078307008 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django INFO 2025-03-22 18:58:14,073 views 102535 140700078307008 User asked for personal data stored: 
django.request ERROR 2025-03-22 18:58:14,081 log 102535 140700078307008 Internal Server Error: /home/accounts/view_data/
Traceback (most recent call last):
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/SustainableApplication/home/views.py", line 279, in view_user_data
    "hashed_password": user.password  # Django stores hashed passwords
                       ^^^^^^^^^^^^^
  File "/home/finn/Group-Engineering-Project/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'password'
django.server ERROR 2025-03-22 18:58:14,082 basehttp 102535 140700078307008 "GET /home/accounts/view_data/ HTTP/1.1" 500 80775
django.server INFO 2025-03-22 18:58:14,664 basehttp 102535 140700078307008 "GET /home/accounts/login/ HTTP/1.1" 200 7747
django.security.SuspiciousSession WARNING 2025-03-22 19:01:29,154 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:29,155 basehttp 102535 140700078307008 "GET /home/accounts/login/ HTTP/1.1" 200 6785
django.server INFO 2025-03-22 19:01:29,208 basehttp 102535 140700078307008 "GET /static/auth.css HTTP/1.1" 200 1844
django.server INFO 2025-03-22 19:01:29,221 basehttp 102535 140700078307008 "GET /static/images/signin.jpg HTTP/1.1" 200 482362
django.request WARNING 2025-03-22 19:01:29,275 log 102535 140700078307008 Not Found: /favicon.ico
django.server WARNING 2025-03-22 19:01:29,275 basehttp 102535 140700078307008 "GET /favicon.ico HTTP/1.1" 404 5745
django.security.SuspiciousSession WARNING 2025-03-22 19:01:30,982 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:30,983 basehttp 102535 140700078307008 "GET /home/ HTTP/1.1" 302 0
django.security.SuspiciousSession WARNING 2025-03-22 19:01:30,991 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:30,991 basehttp 102535 140700078307008 "GET /accounts/login/?next=/home/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:31,569 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:31,570 basehttp 102535 140700078307008 "GET /get_location/1/ HTTP/1.1" 302 0
django.security.SuspiciousSession WARNING 2025-03-22 19:01:31,577 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:31,577 basehttp 102535 140700078307008 "GET /accounts/login/?next=/get_location/1/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:32,043 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:32,044 basehttp 102535 140700078307008 "GET /home/accounts/login/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:32,488 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:32,489 basehttp 102535 140700078307008 "GET /leaderboard/ HTTP/1.1" 302 0
django.security.SuspiciousSession WARNING 2025-03-22 19:01:32,500 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:32,500 basehttp 102535 140700078307008 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:32,861 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:32,861 basehttp 102535 140700078307008 "GET /collectables/ HTTP/1.1" 302 0
django.security.SuspiciousSession WARNING 2025-03-22 19:01:32,871 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:32,871 basehttp 102535 140700078307008 "GET /accounts/login/?next=/collectables/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:33,314 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:33,314 basehttp 102535 140700078307008 "GET /lootboxes/open/ HTTP/1.1" 302 0
django.security.SuspiciousSession WARNING 2025-03-22 19:01:33,321 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:33,322 basehttp 102535 140700078307008 "GET /accounts/login/?next=/lootboxes/open/ HTTP/1.1" 200 6785
django.security.SuspiciousSession WARNING 2025-03-22 19:01:35,156 base 102535 140700078307008 Session data corrupted
django.server INFO 2025-03-22 19:01:35,156 basehttp 102535 140700078307008 "GET /home/signup/ HTTP/1.1" 200 7974
django.security.SuspiciousSession WARNING 2025-03-22 19:01:44,785 base 102535 140700078307008 Session data corrupted
django INFO 2025-03-22 19:01:44,813 views 102535 140700078307008 User logged in: asdasd
django INFO 2025-03-22 19:01:44,815 views 102535 140700078307008 New user signed up: asdasd
django.server INFO 2025-03-22 19:01:44,824 basehttp 102535 140700078307008 "POST /home/signup/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 19:01:44,832 basehttp 102535 140700078307008 "GET /home/ HTTP/1.1" 200 7949
django.server INFO 2025-03-22 19:01:44,948 basehttp 102535 140700078307008 "GET /static/images/Top_Image.jpg HTTP/1.1" 200 1041735
django.server INFO 2025-03-22 19:01:44,948 basehttp 102535 140700064138944 "GET /static/images/Bottom_Image.jpg HTTP/1.1" 200 886653
django.server INFO 2025-03-22 19:01:46,592 basehttp 102535 140700078307008 "GET /home/ HTTP/1.1" 200 7949
django.utils.autoreload INFO 2025-03-22 20:35:54,650 autoreload 132549 139625343238272 Watching for file changes with StatReloader
django.server INFO 2025-03-22 20:35:56,479 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 6785
django.server INFO 2025-03-22 20:35:56,543 basehttp 132549 139625226041024 "GET /static/auth.css HTTP/1.1" 200 1844
django.server INFO 2025-03-22 20:35:56,546 basehttp 132549 139625226041024 "GET /static/images/signin.jpg HTTP/1.1" 200 482362
django.request WARNING 2025-03-22 20:35:56,671 log 132549 139625226041024 Not Found: /favicon.ico
django.server WARNING 2025-03-22 20:35:56,671 basehttp 132549 139625226041024 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 20:35:58,637 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 7974
django.server INFO 2025-03-22 20:36:42,791 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 7574
django.server INFO 2025-03-22 20:36:57,779 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 8405
django.server INFO 2025-03-22 20:37:15,688 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 8405
django.server INFO 2025-03-22 20:37:17,454 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 7616
django.server INFO 2025-03-22 20:37:19,192 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 7616
django.server INFO 2025-03-22 20:37:20,151 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 8405
django WARNING 2025-03-22 20:37:34,551 views 132549 139625226041024 Failed signup attempt.
django.server INFO 2025-03-22 20:37:34,552 basehttp 132549 139625226041024 "POST /home/signup/ HTTP/1.1" 200 8642
django INFO 2025-03-22 20:37:45,821 views 132549 139625226041024 User logged in: thisishell
django INFO 2025-03-22 20:37:45,823 views 132549 139625226041024 New user signed up: thisishell
django.server INFO 2025-03-22 20:37:45,835 basehttp 132549 139625226041024 "POST /home/signup/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 20:37:45,843 basehttp 132549 139625226041024 "GET /home/ HTTP/1.1" 200 8639
django.server INFO 2025-03-22 20:37:45,943 basehttp 132549 139625226041024 "GET /static/images/Top_Image.jpg HTTP/1.1" 200 1041735
django.server INFO 2025-03-22 20:37:45,944 basehttp 132549 139625211872960 "GET /static/images/Bottom_Image.jpg HTTP/1.1" 200 886653
django.server INFO 2025-03-22 20:37:47,896 basehttp 132549 139625226041024 "GET /home/ HTTP/1.1" 200 8639
django.server INFO 2025-03-22 20:37:48,805 basehttp 132549 139625226041024 "GET /get_location/1/ HTTP/1.1" 200 11183
django.server WARNING 2025-03-22 20:37:48,864 basehttp 132549 139625211872960 "GET /static/css/button.css HTTP/1.1" 404 1969
django.server INFO 2025-03-22 20:37:48,864 basehttp 132549 139625226041024 "GET /static/checkin.css HTTP/1.1" 200 1150
django.server INFO 2025-03-22 20:37:48,864 basehttp 132549 139625203480256 "GET /static/css/map.css HTTP/1.1" 200 851
django.server INFO 2025-03-22 20:37:48,871 basehttp 132549 139625203480256 "GET /static/js/checkin.js HTTP/1.1" 200 1980
django.server INFO 2025-03-22 20:37:48,872 basehttp 132549 139625226041024 "GET /static/images/checkin.jpg HTTP/1.1" 200 482362
django.server WARNING 2025-03-22 20:37:48,901 basehttp 132549 139625211872960 "GET /static/css/button.css HTTP/1.1" 404 1969
django.request WARNING 2025-03-22 20:44:36,197 log 132549 139625226041024 Not Found: /favicon.ico
django.server WARNING 2025-03-22 20:44:36,197 basehttp 132549 139625226041024 "GET /favicon.ico HTTP/1.1" 404 5745
django.security.csrf WARNING 2025-03-22 20:44:37,951 log 132549 139625226041024 Forbidden (CSRF token from POST incorrect.): /home/signup/
django.server WARNING 2025-03-22 20:44:37,951 basehttp 132549 139625226041024 "POST /home/signup/ HTTP/1.1" 403 2503
django.server INFO 2025-03-22 20:44:39,205 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 9179
django.server INFO 2025-03-22 20:44:40,659 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 8927
django.server INFO 2025-03-22 20:44:42,431 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 8927
django.server INFO 2025-03-22 20:44:55,777 basehttp 132549 139625226041024 "GET /home/accounts/login/ HTTP/1.1" 200 8927
django.request WARNING 2025-03-22 20:44:55,987 log 132549 139625226041024 Not Found: /favicon.ico
django.server WARNING 2025-03-22 20:44:55,987 basehttp 132549 139625226041024 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 20:44:56,764 basehttp 132549 139625226041024 "GET /home/signup/ HTTP/1.1" 200 9726
django.utils.autoreload INFO 2025-03-22 20:48:58,522 autoreload 132549 139625343238272 /home/finn/Group-Engineering-Project/SustainableApplication/SustainableApplication/settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-22 20:48:58,764 autoreload 135738 140180470964352 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-22 20:49:15,654 autoreload 135738 140180470964352 /home/finn/Group-Engineering-Project/SustainableApplication/SustainableApplication/settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-22 20:49:15,838 autoreload 135863 139955367571584 Watching for file changes with StatReloader
django.server INFO 2025-03-22 20:49:21,589 basehttp 135863 139955316717248 "GET /home/signup/ HTTP/1.1" 200 9726
django.request WARNING 2025-03-22 20:49:21,756 log 135863 139955316717248 Not Found: /favicon.ico
django.server WARNING 2025-03-22 20:49:21,757 basehttp 135863 139955316717248 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 20:49:23,514 basehttp 135863 139955316717248 "GET /home/accounts/login/ HTTP/1.1" 200 8927
django INFO 2025-03-22 20:49:28,178 views 135863 139955316717248 User logged in: nightmare
django.server INFO 2025-03-22 20:49:28,191 basehttp 135863 139955316717248 "POST /home/accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 20:49:28,201 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 8639
django.server INFO 2025-03-22 20:49:29,383 basehttp 135863 139955316717248 "GET /home/accounts/login/ HTTP/1.1" 200 8927
django INFO 2025-03-22 20:54:31,337 views 135863 139955316717248 User logged in: nightmare
django.server INFO 2025-03-22 20:54:31,349 basehttp 135863 139955316717248 "POST /home/accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 20:54:31,362 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 9081
django.request WARNING 2025-03-22 20:54:31,545 log 135863 139955316717248 Not Found: /favicon.ico
django.server WARNING 2025-03-22 20:54:31,545 basehttp 135863 139955316717248 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 20:57:18,781 basehttp 135863 139955316717248 "GET /leaderboard/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 20:57:18,794 basehttp 135863 139955316717248 "GET /accounts/login/?next=/leaderboard/ HTTP/1.1" 200 8153
django.server INFO 2025-03-22 20:57:19,099 basehttp 135863 139955316717248 "GET /static/auth.css HTTP/1.1" 200 1844
django.server INFO 2025-03-22 20:57:19,111 basehttp 135863 139955316717248 "GET /static/images/signin.jpg HTTP/1.1" 200 482362
django.request WARNING 2025-03-22 20:57:19,169 log 135863 139955316717248 Not Found: /favicon.ico
django INFO 2025-03-22 20:57:25,209 views 135863 139955316717248 User logged in: nightmare
django.server INFO 2025-03-22 20:57:25,221 basehttp 135863 139955316717248 "POST /accounts/login/?next=/leaderboard/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 20:57:25,234 basehttp 135863 139955316717248 "GET /leaderboard/ HTTP/1.1" 200 9287
django.server INFO 2025-03-22 20:57:25,335 basehttp 135863 139955316717248 "GET /static/leaderboard.css HTTP/1.1" 200 1892
django.server INFO 2025-03-22 20:57:25,359 basehttp 135863 139955307275968 "GET /static/images/leaderboardBottom_v2.jpg HTTP/1.1" 200 31621
django.server INFO 2025-03-22 20:57:25,361 basehttp 135863 139955316717248 "GET /static/images/leaderboardTop_v2.jpg HTTP/1.1" 200 1165356
django.server INFO 2025-03-22 20:57:30,238 basehttp 135863 139955316717248 "GET /lootboxes/open/ HTTP/1.1" 200 11179
django.server WARNING 2025-03-22 20:57:30,304 basehttp 135863 139955316717248 "GET /static/css/open_lootbox.css HTTP/1.1" 404 1987
django.server INFO 2025-03-22 20:57:30,308 basehttp 135863 139955316717248 "GET /static/images/lootbox.png HTTP/1.1" 200 19128
django.server INFO 2025-03-22 20:57:30,313 basehttp 135863 139955307275968 "GET /static/images/lootboxes_v4.jpg HTTP/1.1" 200 2674413
django.server WARNING 2025-03-22 20:57:30,329 basehttp 135863 139955316717248 "GET /static/css/open_lootbox.css HTTP/1.1" 404 1987
django.server INFO 2025-03-22 20:57:31,039 basehttp 135863 139955307275968 "GET /collectables/ HTTP/1.1" 200 6119
django.server INFO 2025-03-22 20:57:31,854 basehttp 135863 139955307275968 "GET /leaderboard/ HTTP/1.1" 200 9287
django.server INFO 2025-03-22 20:57:32,680 basehttp 135863 139955307275968 "GET /collectables/ HTTP/1.1" 200 6119
django.server INFO 2025-03-22 20:57:33,997 basehttp 135863 139955307275968 "GET /collectables/ HTTP/1.1" 200 6119
django.server INFO 2025-03-22 20:57:34,318 basehttp 135863 139955307275968 "GET /lootboxes/open/ HTTP/1.1" 200 11179
django.server WARNING 2025-03-22 20:57:34,381 basehttp 135863 139955307275968 "GET /static/css/open_lootbox.css HTTP/1.1" 404 1987
django.server WARNING 2025-03-22 20:57:34,405 basehttp 135863 139955307275968 "GET /static/css/open_lootbox.css HTTP/1.1" 404 1987
django.server INFO 2025-03-22 20:57:49,862 basehttp 135863 139955307275968 "GET /leaderboard/ HTTP/1.1" 200 9287
django.server INFO 2025-03-22 21:00:33,658 basehttp 135863 139955307275968 "GET /home/ HTTP/1.1" 200 9181
django.request WARNING 2025-03-22 21:00:33,872 log 135863 139955307275968 Not Found: /favicon.ico
django.server WARNING 2025-03-22 21:00:33,873 basehttp 135863 139955307275968 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 21:00:35,768 basehttp 135863 139955307275968 "GET /home/ HTTP/1.1" 200 9181
django.server INFO 2025-03-22 21:01:53,653 basehttp 135863 139955316717248 "GET /leaderboard/ HTTP/1.1" 200 9287
django.server INFO 2025-03-22 21:01:55,249 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 9181
django.server INFO 2025-03-22 21:01:55,314 basehttp 135863 139955316717248 "GET /static/images/Top_Image.jpg HTTP/1.1" 304 0
django.server INFO 2025-03-22 21:01:55,316 basehttp 135863 139955297834688 "GET /static/images/Bottom_Image.jpg HTTP/1.1" 304 0
django.server INFO 2025-03-22 21:03:11,895 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 9181
django.server INFO 2025-03-22 21:03:12,731 basehttp 135863 139955316717248 "GET /leaderboard/ HTTP/1.1" 200 9287
django.server INFO 2025-03-22 21:03:52,214 basehttp 135863 139955297834688 "GET /home/ HTTP/1.1" 200 9065
django.request WARNING 2025-03-22 21:03:52,403 log 135863 139955297834688 Not Found: /favicon.ico
django.server WARNING 2025-03-22 21:03:52,403 basehttp 135863 139955297834688 "GET /favicon.ico HTTP/1.1" 404 5745
django.server INFO 2025-03-22 21:05:12,908 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 9065
django.server INFO 2025-03-22 21:05:13,655 basehttp 135863 139955316717248 "GET /home/ HTTP/1.1" 200 9065
django.server INFO 2025-03-22 21:05:14,794 basehttp 135863 139955316717248 "GET /map/ HTTP/1.1" 200 9595
django.server INFO 2025-03-22 21:05:14,863 basehttp 135863 139955316717248 "GET /media/buildings/Sports_park_pixel_locked.png HTTP/1.1" 200 9801
django.server INFO 2025-03-22 21:05:14,866 basehttp 135863 139955307275968 "GET /media/buildings/Forum_locked.png HTTP/1.1" 200 26454
django.server INFO 2025-03-22 21:05:14,871 basehttp 135863 139955289441984 "GET /media/items/solar_panel_heFXH0T.png HTTP/1.1" 200 292058
django.server INFO 2025-03-22 21:05:14,871 basehttp 135863 139955281049280 "GET /media/items/tree_TrrWjHH_UCFOgZZ.png HTTP/1.1" 200 85207
django.server INFO 2025-03-22 21:05:14,939 basehttp 135863 139955289441984 "GET /static/images/grass_background.png HTTP/1.1" 200 967284
django.server INFO 2025-03-22 21:05:16,608 basehttp 135863 139955289441984 "GET /shop/ HTTP/1.1" 200 8532
django.server INFO 2025-03-22 21:05:18,075 basehttp 135863 139955289441984 "GET /map/ HTTP/1.1" 200 9595
django.server INFO 2025-03-22 21:05:18,815 basehttp 135863 139955289441984 "GET /home/ HTTP/1.1" 200 9065
django.server INFO 2025-03-22 21:05:19,836 basehttp 135863 139955289441984 "GET /map/ HTTP/1.1" 200 9595
django.server INFO 2025-03-22 21:05:20,456 basehttp 135863 139955289441984 "GET /shop/ HTTP/1.1" 200 8532
django.server INFO 2025-03-22 21:05:20,730 basehttp 135863 139955289441984 "POST /buy/item/2/ HTTP/1.1" 302 0
django.server INFO 2025-03-22 21:05:20,742 basehttp 135863 139955289441984 "GET /shop/ HTTP/1.1" 200 8930
django.server INFO 2025-03-22 21:05:22,042 basehttp 135863 139955289441984 "GET /map/ HTTP/1.1" 200 9706
django.server INFO 2025-03-22 21:05:24,545 basehttp 135863 139955289441984 "GET /shop/ HTTP/1.1" 200 8532
