django INFO 2025-02-24 13:45:58,056 views 1288 34744 User asked for personal data stored: matt4
django INFO 2025-02-25 10:18:26,333 views 13908 15252 User asked for personal data stored: matt4
django INFO 2025-02-25 10:18:26,664 views 13908 15252 User logged in: testuser
django INFO 2025-02-25 10:27:41,371 views 1992 18244 User logged in: testuser
django.request WARNING 2025-02-25 10:27:41,411 log 1992 18244 Bad Request: /get_location/1/
django INFO 2025-02-25 10:27:41,736 views 1992 18244 User logged in: testuser
django.request WARNING 2025-02-25 10:27:41,761 log 1992 18244 Bad Request: /get_location/1/
django INFO 2025-02-25 10:27:42,081 views 1992 18244 User logged in: testuser
django.request WARNING 2025-02-25 10:27:42,103 log 1992 18244 Bad Request: /get_location/1/
django INFO 2025-02-25 10:27:42,432 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:42,799 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:43,141 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:43,491 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:43,841 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:43,886 views 1992 18244 Logout by an unauthenticated user or session end.
django INFO 2025-02-25 10:27:45,175 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:45,201 views 1992 18244 User deleted account: testuser
django INFO 2025-02-25 10:27:45,841 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:45,863 views 1992 18244 User deleted account: testuser
django INFO 2025-02-25 10:27:46,516 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:46,539 views 1992 18244 User deleted account: testuser
django INFO 2025-02-25 10:27:46,861 views 1992 18244 Failed login attempt for username: testuser
django INFO 2025-02-25 10:27:48,162 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:50,144 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:27:50,168 views 1992 18244 User logged out: testuser
django INFO 2025-02-25 10:27:50,841 views 1992 18244 User logged in: newuser
django INFO 2025-02-25 10:27:50,861 views 1992 18244 New user signed up: newuser
django INFO 2025-02-25 10:27:51,515 views 1992 18244 Failed login attempt for username: TESTUSER
django INFO 2025-02-25 10:27:52,165 views 1992 18244 Failed login attempt for username: TESTUSER@EXAMPLE.COM
django INFO 2025-02-25 10:27:53,461 views 1992 18244 User logged in: testuser
django WARNING 2025-02-25 10:27:53,803 views 1992 18244 Failed signup attempt.
django INFO 2025-02-25 10:27:54,776 views 1992 18244 User logged in: newuser
django INFO 2025-02-25 10:27:54,794 views 1992 18244 New user signed up: newuser
django WARNING 2025-02-25 10:27:55,121 views 1992 18244 Failed signup attempt.
django INFO 2025-02-25 10:27:55,775 views 1992 18244 Failed login attempt for username: ' OR '1'='1
django WARNING 2025-02-25 10:27:56,101 views 1992 18244 Failed signup attempt.
django WARNING 2025-02-25 10:27:56,421 views 1992 18244 Failed signup attempt.
django INFO 2025-02-25 10:27:57,063 views 1992 18244 User logged in: matt4
django INFO 2025-02-25 10:27:57,104 views 1992 18244 User asked for personal data stored: matt4
django INFO 2025-02-25 10:27:57,784 views 1992 18244 User logged in: matt4
django INFO 2025-02-25 10:27:57,834 views 1992 18244 User asked for personal data stored: matt4
django INFO 2025-02-25 10:27:58,511 views 1992 18244 User logged in: matt4
django INFO 2025-02-25 10:27:58,551 views 1992 18244 User asked for personal data stored: matt4
django INFO 2025-02-25 10:27:58,913 views 1992 18244 User logged in: testuser
django INFO 2025-02-25 10:28:48,465 views 31236 27216 User logged in: testuser
django.request WARNING 2025-02-25 10:28:48,500 log 31236 27216 Bad Request: /get_location/1/
django INFO 2025-02-25 10:28:48,827 views 31236 27216 User logged in: testuser
django.request WARNING 2025-02-25 10:28:48,856 log 31236 27216 Bad Request: /get_location/1/
django INFO 2025-02-25 10:28:49,188 views 31236 27216 User logged in: testuser
django.request WARNING 2025-02-25 10:28:49,211 log 31236 27216 Bad Request: /get_location/1/
django INFO 2025-02-25 10:28:49,527 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:49,896 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:50,256 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:50,616 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:50,668 views 31236 27216 Logout by an unauthenticated user or session end.
django INFO 2025-02-25 10:28:52,001 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:52,029 views 31236 27216 User deleted account: testuser
django INFO 2025-02-25 10:28:52,671 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:52,691 views 31236 27216 User deleted account: testuser
django INFO 2025-02-25 10:28:53,331 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:53,361 views 31236 27216 User deleted account: testuser
django INFO 2025-02-25 10:28:53,686 views 31236 27216 Failed login attempt for username: testuser
django INFO 2025-02-25 10:28:54,981 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:56,961 views 31236 27216 User logged in: testuser
django INFO 2025-02-25 10:28:56,985 views 31236 27216 User logged out: testuser
django INFO 2025-02-25 10:28:57,632 views 31236 27216 User logged in: newuser
django INFO 2025-02-25 10:28:57,651 views 31236 27216 New user signed up: newuser
django INFO 2025-02-25 10:28:58,294 views 31236 27216 Failed login attempt for username: TESTUSER
django INFO 2025-02-25 10:28:58,945 views 31236 27216 Failed login attempt for username: TESTUSER@EXAMPLE.COM
django INFO 2025-02-25 10:29:00,222 views 31236 27216 User logged in: testuser
django WARNING 2025-02-25 10:29:00,573 views 31236 27216 Failed signup attempt.
django INFO 2025-02-25 10:29:01,531 views 31236 27216 User logged in: newuser
django INFO 2025-02-25 10:29:01,553 views 31236 27216 New user signed up: newuser
django WARNING 2025-02-25 10:29:01,881 views 31236 27216 Failed signup attempt.
django INFO 2025-02-25 10:29:02,521 views 31236 27216 Failed login attempt for username: ' OR '1'='1
django WARNING 2025-02-25 10:29:02,846 views 31236 27216 Failed signup attempt.
django WARNING 2025-02-25 10:29:03,163 views 31236 27216 Failed signup attempt.
django INFO 2025-02-25 10:29:03,802 views 31236 27216 User logged in: matt4
django INFO 2025-02-25 10:29:03,844 views 31236 27216 User asked for personal data stored: matt4
django INFO 2025-02-25 10:29:04,524 views 31236 27216 User logged in: matt4
django INFO 2025-02-25 10:29:04,574 views 31236 27216 User asked for personal data stored: matt4
django INFO 2025-02-25 10:29:05,253 views 31236 27216 User logged in: matt4
django INFO 2025-02-25 10:29:05,291 views 31236 27216 User asked for personal data stored: matt4
django INFO 2025-02-25 10:29:05,650 views 31236 27216 User logged in: testuser
django.utils.autoreload INFO 2025-02-25 10:31:25,894 autoreload 6152 11932 Watching for file changes with StatReloader
django.server INFO 2025-02-25 10:31:27,423 basehttp 6152 3888 "GET / HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:31:27,485 basehttp 6152 3888 "GET /accounts/login/ HTTP/1.1" 200 1424
django.server WARNING 2025-02-25 10:31:27,603 basehttp 6152 3888 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:31:32,804 views 6152 33632 User logged in: matt
django.server INFO 2025-02-25 10:31:32,922 basehttp 6152 33632 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:31:32,967 basehttp 6152 33632 "GET /home/ HTTP/1.1" 200 1682
django.server WARNING 2025-02-25 10:31:33,056 basehttp 6152 33632 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:31:38,302 basehttp 6152 12928 "GET /leaderboard/ HTTP/1.1" 200 608
django.server INFO 2025-02-25 10:31:38,473 basehttp 6152 12928 "GET /static/leaderboard/styles.css HTTP/1.1" 200 725
django.server INFO 2025-02-25 10:31:45,331 basehttp 6152 12928 "GET /tasks/ HTTP/1.1" 200 3439
django.server WARNING 2025-02-25 10:31:45,385 basehttp 6152 12928 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:31:48,682 basehttp 6152 32576 "GET /get_location/1/? HTTP/1.1" 200 2198
django.server INFO 2025-02-25 10:31:48,735 basehttp 6152 32576 "GET /static/css/button.css HTTP/1.1" 304 0
django.server INFO 2025-02-25 10:31:50,747 basehttp 6152 32576 "GET /get_location/1/?lat=50.7309945&lon=-3.5420185 HTTP/1.1" 200 2069
django.server INFO 2025-02-25 10:31:55,816 basehttp 6152 32576 "GET /tasks/ HTTP/1.1" 200 3439
django.server WARNING 2025-02-25 10:31:55,863 basehttp 6152 32576 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:32:01,205 basehttp 6152 8884 "GET /home/ HTTP/1.1" 200 1682
django.server WARNING 2025-02-25 10:32:01,261 basehttp 6152 8884 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:32:05,423 views 6152 9008 User asked for personal data stored: matt
django.server INFO 2025-02-25 10:32:05,442 basehttp 6152 9008 "GET /home/accounts/view_data/ HTTP/1.1" 200 1316
django.server WARNING 2025-02-25 10:32:05,491 basehttp 6152 9008 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:32:13,208 basehttp 6152 10572 "GET /home/ HTTP/1.1" 200 1682
django.server WARNING 2025-02-25 10:32:13,277 basehttp 6152 10572 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:32:16,880 basehttp 6152 13996 "GET /home/accounts/update_profile/ HTTP/1.1" 200 1521
django.server WARNING 2025-02-25 10:32:16,931 basehttp 6152 13996 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:32:19,359 views 6152 30884 User updated profile (username & email): matt123
django.server INFO 2025-02-25 10:32:19,360 basehttp 6152 30884 "POST /home/accounts/update_profile/ HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:32:19,384 basehttp 6152 30884 "GET /home/ HTTP/1.1" 200 1685
django.server WARNING 2025-02-25 10:32:19,439 basehttp 6152 30884 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:32:20,914 views 6152 21280 User asked for personal data stored: matt123
django.server INFO 2025-02-25 10:32:20,932 basehttp 6152 21280 "GET /home/accounts/view_data/ HTTP/1.1" 200 1355
django.server WARNING 2025-02-25 10:32:20,984 basehttp 6152 21280 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:32:26,855 basehttp 6152 7580 "GET /home/ HTTP/1.1" 200 1685
django.server WARNING 2025-02-25 10:32:26,933 basehttp 6152 7580 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:32:27,581 views 6152 33636 User logged out: matt123
django.server INFO 2025-02-25 10:32:27,581 basehttp 6152 33636 "GET /home/accounts/logout/ HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:32:27,588 basehttp 6152 33636 "GET /home/accounts/login/ HTTP/1.1" 200 1424
django.server WARNING 2025-02-25 10:32:27,666 basehttp 6152 33636 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.utils.autoreload INFO 2025-02-25 10:34:04,970 autoreload 32424 26292 Watching for file changes with StatReloader
django.server INFO 2025-02-25 10:34:08,203 basehttp 32424 20600 "GET / HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:34:08,246 basehttp 32424 20600 "GET /accounts/login/ HTTP/1.1" 200 1424
django.server WARNING 2025-02-25 10:34:08,349 basehttp 32424 20600 "GET /static/css/styles.css HTTP/1.1" 404 1969
django INFO 2025-02-25 10:34:16,384 views 32424 26132 User logged in: dc754
django.server INFO 2025-02-25 10:34:16,466 basehttp 32424 26132 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:34:16,506 basehttp 32424 26132 "GET /home/ HTTP/1.1" 200 1735
django.server WARNING 2025-02-25 10:34:16,554 basehttp 32424 26132 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:34:18,192 basehttp 32424 26520 "GET /PrivacyPolicy/ HTTP/1.1" 200 72592
django.utils.autoreload INFO 2025-02-25 10:36:25,646 autoreload 32828 8920 Watching for file changes with StatReloader
django.server INFO 2025-02-25 10:36:27,353 basehttp 32828 21672 "GET / HTTP/1.1" 302 0
django.server INFO 2025-02-25 10:36:27,402 basehttp 32828 21672 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server WARNING 2025-02-25 10:36:27,500 basehttp 32828 21672 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:36:30,799 basehttp 32828 17860 "GET /TermsAndConditions/ HTTP/1.1" 200 34408
django.server INFO 2025-02-25 10:36:32,793 basehttp 32828 17860 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-02-25 10:36:34,106 basehttp 32828 17860 "GET /PrivacyPolicy/ HTTP/1.1" 200 72592
django.server INFO 2025-02-25 10:36:35,285 basehttp 32828 17860 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-02-25 10:36:38,299 basehttp 32828 17860 "GET /home/signup/ HTTP/1.1" 200 2526
django.server WARNING 2025-02-25 10:36:38,349 basehttp 32828 17860 "GET /static/css/styles.css HTTP/1.1" 404 1969
django.server INFO 2025-02-25 10:36:39,652 basehttp 32828 10572 "GET /PrivacyPolicy/ HTTP/1.1" 200 72592
django.server INFO 2025-02-25 10:36:42,199 basehttp 32828 10572 "GET /TermsAndConditions/ HTTP/1.1" 200 34408
django.utils.autoreload INFO 2025-03-18 21:38:40,783 autoreload 26264 24128 Watching for file changes with StatReloader
django.server INFO 2025-03-18 21:38:43,172 basehttp 26264 28004 "GET / HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:38:43,389 basehttp 26264 28004 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-03-18 21:38:43,582 basehttp 26264 28004 "GET /static/css/styles.css HTTP/1.1" 200 180
django.request WARNING 2025-03-18 21:38:43,874 log 26264 28004 Not Found: /favicon.ico
django.server WARNING 2025-03-18 21:38:43,875 basehttp 26264 28004 "GET /favicon.ico HTTP/1.1" 404 4578
django INFO 2025-03-18 21:38:46,280 views 26264 28004 User logged in: dc754
django.server INFO 2025-03-18 21:38:46,320 basehttp 26264 28004 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:38:46,339 basehttp 26264 28004 "GET /home/ HTTP/1.1" 200 1790
django.request ERROR 2025-03-18 21:38:49,051 log 26264 28004 Internal Server Error: /collectables/
Traceback (most recent call last):
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: collectables_collectable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dc754\OneDrive\Documents\year2\softwareEngineering\Group-Engineering-Project\SustainableApplication\collectables\views.py", line 16, in collectable_gallery
    return render(request, "gallery.html", context)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: collectables_collectable
django.server ERROR 2025-03-18 21:38:49,077 basehttp 26264 28004 "GET /collectables/ HTTP/1.1" 500 177304
django.utils.autoreload INFO 2025-03-18 21:44:42,355 autoreload 12252 22576 Watching for file changes with StatReloader
django.server INFO 2025-03-18 21:44:43,856 basehttp 12252 26880 "GET / HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:44:43,934 basehttp 12252 26880 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-03-18 21:44:44,044 basehttp 12252 26880 "GET /static/css/styles.css HTTP/1.1" 304 0
django INFO 2025-03-18 21:44:46,207 views 12252 26880 User logged in: dc754
django.server INFO 2025-03-18 21:44:46,251 basehttp 12252 26880 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:44:46,272 basehttp 12252 26880 "GET /home/ HTTP/1.1" 200 1790
django.request ERROR 2025-03-18 21:44:47,488 log 12252 26880 Internal Server Error: /collectables/
Traceback (most recent call last):
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: home_customuser_collectables_owned

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\dc754\OneDrive\Documents\year2\softwareEngineering\Group-Engineering-Project\SustainableApplication\collectables\views.py", line 16, in collectable_gallery
    return render(request, "gallery.html", context)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dc754\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: home_customuser_collectables_owned
django.server ERROR 2025-03-18 21:44:47,502 basehttp 12252 26880 "GET /collectables/ HTTP/1.1" 500 177544
django.utils.autoreload INFO 2025-03-18 21:45:58,811 autoreload 3708 20876 Watching for file changes with StatReloader
django.server INFO 2025-03-18 21:46:00,651 basehttp 3708 20352 "GET / HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:46:00,725 basehttp 3708 20352 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-03-18 21:46:00,843 basehttp 3708 20352 "GET /static/css/styles.css HTTP/1.1" 304 0
django INFO 2025-03-18 21:46:03,070 views 3708 20352 User logged in: dc754
django.server INFO 2025-03-18 21:46:03,123 basehttp 3708 20352 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-18 21:46:03,145 basehttp 3708 20352 "GET /home/ HTTP/1.1" 200 1790
django.server INFO 2025-03-18 21:46:04,248 basehttp 3708 20352 "GET /collectables/ HTTP/1.1" 200 255
django.utils.autoreload INFO 2025-03-18 22:03:28,703 autoreload 4068 27784 Watching for file changes with StatReloader
django.utils.autoreload INFO 2025-03-18 22:03:54,950 autoreload 4068 27784 C:\Users\dc754\OneDrive\Documents\year2\softwareEngineering\Group-Engineering-Project\SustainableApplication\SustainableApplication\settings.py changed, reloading.
django.utils.autoreload INFO 2025-03-18 22:04:07,097 autoreload 17568 12188 Watching for file changes with StatReloader
django.server INFO 2025-03-18 22:04:08,815 basehttp 17568 27328 "GET / HTTP/1.1" 302 0
django.server INFO 2025-03-18 22:04:08,845 basehttp 17568 27328 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-03-18 22:04:08,881 basehttp 17568 27328 "GET /static/css/styles.css HTTP/1.1" 304 0
django INFO 2025-03-18 22:04:10,761 views 17568 27328 User logged in: dc754
django.server INFO 2025-03-18 22:04:10,785 basehttp 17568 27328 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-18 22:04:10,795 basehttp 17568 27328 "GET /home/ HTTP/1.1" 200 1842
django.server INFO 2025-03-18 22:04:11,936 basehttp 17568 27328 "GET /lootboxes/open/ HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:13,658 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:14,529 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:15,015 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:15,229 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:15,439 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:15,673 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:15,911 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:16,293 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:16,480 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:16,878 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:17,112 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:17,550 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:17,975 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:18,393 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:18,621 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:18,843 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:19,071 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:19,670 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:19,901 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:20,412 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:20,622 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:21,018 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:21,462 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:21,865 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:22,098 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:22,328 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:22,554 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:22,987 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:04:23,413 basehttp 17568 27328 "GET /lootboxes/open/? HTTP/1.1" 200 357
django.utils.autoreload INFO 2025-03-18 22:08:34,141 autoreload 27304 3612 Watching for file changes with StatReloader
django.server INFO 2025-03-18 22:08:35,369 basehttp 27304 17328 "GET / HTTP/1.1" 302 0
django.server INFO 2025-03-18 22:08:35,413 basehttp 27304 17328 "GET /accounts/login/ HTTP/1.1" 200 1539
django.server INFO 2025-03-18 22:08:35,453 basehttp 27304 17328 "GET /static/css/styles.css HTTP/1.1" 304 0
django INFO 2025-03-18 22:08:37,043 views 27304 17328 User logged in: dc754
django.server INFO 2025-03-18 22:08:37,065 basehttp 27304 17328 "POST /accounts/login/ HTTP/1.1" 302 0
django.server INFO 2025-03-18 22:08:37,075 basehttp 27304 17328 "GET /home/ HTTP/1.1" 200 1842
django.server INFO 2025-03-18 22:08:38,070 basehttp 27304 17328 "GET /lootboxes/open/ HTTP/1.1" 200 357
django.server INFO 2025-03-18 22:08:39,342 basehttp 27304 17328 "GET /lootboxes/open/? HTTP/1.1" 200 519
django.request WARNING 2025-03-18 22:08:39,375 log 27304 17328 Not Found: /media/media/business_school.jpg
django.server WARNING 2025-03-18 22:08:39,376 basehttp 27304 17328 "GET /media/media/business_school.jpg HTTP/1.1" 404 5093
django.server INFO 2025-03-18 22:08:50,216 basehttp 27304 17328 "GET /collectables/ HTTP/1.1" 200 407
django.request WARNING 2025-03-18 22:08:50,245 log 27304 17328 Not Found: /media/media/business_school.jpg
django.server WARNING 2025-03-18 22:08:50,245 basehttp 27304 17328 "GET /media/media/business_school.jpg HTTP/1.1" 404 5093
